server.port=8081
spring.application.name=bfhl-api

# SQL Webhook Configuration
bfhl.webhook.url=https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA
# Replace with your actual access token when needed
bfhl.webhook.token=bajaj_finserv_test_token_2025

# JWT Configuration
jwt.secret=bajajfinservhealthlimitedjavacodingtestauthentication
jwt.expiration=86400000

# Request Configuration
# Set to true to enable request debugging
logging.level.org.springframework.web.client.RestTemplate=DEBUG 